apiVersion: v1
kind: Service
metadata:
  name: devops-app-22
spec:
  type: NodePort
  selector:
    app: devops-app-22
  ports:
    - port: 8085 # Service port
      targetPort: 8085 # Container port
      nodePort: 31000 # NodePort between 30000â€“32767
